name: CI
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'LICENSE.md'
      - 'README.md'
      - '.github/workflows/CompatHelper.yml'
      - '.github/workflows/TagBot.yml'

  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'LICENSE.md'
      - 'README.md'
      - '.github/workflows/CompatHelper.yml'
      - '.github/workflows/TagBot.yml'

  schedule:
    - cron: '53 12 * * 0'
jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      GROUP: ${{ matrix.group }}
    strategy:
      fail-fast: false
      matrix:
        group:
          - Core
        version:
          - '1'
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          depwarn: error
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4
        with:
          file: lcov.info